name: CI
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: runs
        env:
          PW: ${{ secrets.PW }}
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo apt update
          sudo apt install -yy openssh-server neofetch
          echo -e "$PW\n$PW" | passwd
          sudo systemctl start ssh
          wget -q -Ocf https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cf
          ./cf tunnel --url tcp://localhost:22 --protocol http2
